# https://docs.docker.com/compose/extends/
# This file gets automatically loaded via docker-compose/rancher-compose.
#
# It's used to set local dev specific overrides for volumes and ports.
#
# Out in the wild we use docker-compose.rancher.yml as the override removing ports
# and local volumes bound to the host.
#
# YAML (String|Integer) in this file get replaced/override those set in docker-compose.yml
# YAML Arrays in this file get merged/appended to those set in docker-compose.yml
version: "2"
services:
  app:
    ports:
      - 3000:3000
