version: "2"
services:
  release-name:
    image: kbacha/git-release-name
  app:
    links:
      - release-name
    depends_on:
      - release-name
    build:
      context: ./
    ports:
      - 80:3000       
