version: "2"
services:
  release-name:
    build:
      context: ./
      dockerfile: ./Dockerfile.worker
  app:
    links:
      - release-name
    depends_on:
      - release-name
    build:
      context: ./
      dockerfile: ./Dockerfile.web
    ports:
      - 80:3000

